// <auto-generated />
using System;
using JqueryAjax.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JqueryAjax.Migrations
{
    [DbContext(typeof(TransactionDBContext))]
    [Migration("20210801145234_AddedDate")]
    partial class AddedDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("JqueryAjax.Models.TransactionModel", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BenificiaryName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("accountNumber")
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("bankName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("swiftCode")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("transactionId");

                    b.ToTable("transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
